name: Ruby Test ðŸ’Ž

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ðŸ’Ž Test with Ruby ${{ matrix.ruby-version }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.1.7'
          - '3.2.8'
          - '3.3.8'
          - '3.4.4'

    runs-on: ubuntu-22.04

    steps:
    - name: ðŸ”„ Checkout Repository
      uses: actions/checkout@v4

    - name: ðŸ› ï¸ Setup Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: â˜ï¸ Set up test cloud
      run: |
        export CLOUDINARY_URL=$(bash tools/get_test_cloud.sh)
        echo "CLOUDINARY_URL=$CLOUDINARY_URL" >> $GITHUB_ENV
        echo "cloud_name: $(echo $CLOUDINARY_URL | cut -d'@' -f2)"

    - name: ðŸ§ª Run tests
      run: bundle exec rspec --format documentation --color
      env:
        CLOUDINARY_URL: ${{ env.CLOUDINARY_URL }}
